<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = ['content', 'post_id'];

    public function user()
    {
        return $this->belongsTo('\App\Models\User');
    }

    public function post()
    {
        return $this->belongsTo('\App\Models\Post');
    }

    public function votes()
    {
        return $this->morphMany('\App\Models\Vote', 'votable');
    }

    public function likeCommentVotes()
    {
        return $this->morphMany('\App\Models\Vote', 'votable')->where('state', 'like');
    }

    public function dislikeCommentVotes()
    {
        return $this->morphMany('\App\Models\Vote', 'votable')->where('state', 'dislike');
    }

    protected static function booted()
    {
//        parent::booted(); // TODO: Change the autogenerated stub
        static::deleting(function ($comment) {
            $comment->votes()->delete();
        });
    }

}
